name: Android CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - 'release/**'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  BUILD_TYPE: "release"

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

      - name: Lint check
        run: ./gradlew lint

      - name: Build APK
        run: ./gradlew assemble${{ env.BUILD_TYPE }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ env.BUILD_TYPE }}-apk
          path: app/build/outputs/apk/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk
